# Generated by Django 3.2.4 on 2021-06-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pollcreator',
            field=models.CharField(default='NoCreator', max_length=50),
        ),
    ]
